# Generated by Django 3.2.13 on 2022-06-22 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'order',
                    models.FloatField(
                        default=1.0,
                        help_text='Actions are run in ascending order.',
                    ),
                ),
                ('name', models.TextField(blank=True, default='')),
                (
                    'method',
                    models.CharField(
                        choices=[('GET', 'GET'), ('POST', 'POST')],
                        max_length=8,
                    ),
                ),
                ('path', models.TextField()),
                (
                    'data',
                    models.TextField(
                        help_text='HTTP parameters in JSON format. Supports string templating. Example: $name or $(name).'
                    ),
                ),
                (
                    'files',
                    models.TextField(
                        help_text='Uploaded files in JSON format. Key and value pairs correspond to filename and file-path pairs. Supports string templating. Example: $name and $(name).'
                    ),
                ),
                ('status_code', models.CharField(max_length=3)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.TextField(unique=True)),
                (
                    'priority',
                    models.FloatField(
                        default=1.0,
                        help_text='Scenarios are run in ascending priority.',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'order',
                    models.FloatField(
                        default=1.0,
                        help_text='Validators are run in ascending order.',
                    ),
                ),
                (
                    'pattern',
                    models.TextField(
                        help_text='Matched against HTTP response. Supports regular expressions. Symbolic group names are stored and may be used for string templating. Example: (?P&lt;name&gt;pattern)'
                    ),
                ),
                (
                    'action',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='validators',
                        to='replay.action',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='scenario',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='replay.scenario',
            ),
        ),
    ]
